default_config:
# http:
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem
group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
frontend:
  themes: !include_dir_merge_named themes
logger:
  default: warning
history:
recorder:
  db_url: 'sqlite:///:memory:'
  exclude:
    entities:
    - sensor.time
    - sensor.time_date
    - binary_sensor.presence_25
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'time_date'
ios:
google_assistant:
  project_id: !secret google_assistant_id
  entity_config:
    group.all_automations:
      expose: false
notify:
  - name: web
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - name: t6m
    platform: telegram
    chat_id: !secret telegram_chat_id
  - name: all
    platform: group
    services:
    - service: web
    - service: t6m
    - service: ios_i7sw
    - service: mi_9_se
  - name: low_priority
    platform: group
    services:
    - service: web
    - service: ios_i7sw
    - service: mi_9_se
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id
asuswrt:
  host: !secret asuswrt_host
  username: !secret asuswrt_username
  port: 35
  ssh_key: /ssl/asuswrt_ssh
  sensors:
    - download_speed
    - upload_speed
    - devices
device_tracker:
  - platform: asuswrt
    new_device_defaults:
      track_new_devices: false
climate:
  - platform: generic_thermostat
    name: Room Heating
    heater: switch.ikea_plug
    target_sensor: sensor.temperature_2
    away_temp: 15
    min_temp: 15
    max_temp: 25
    hot_tolerance: 0.5
    cold_tolerance: 0.5
  - platform: generic_thermostat
    name: Bathroom Heating
    heater: switch.osram_plug_4
    target_sensor: sensor.temperature_7
    away_temp: 15
    min_temp: 15
    max_temp: 25
    hot_tolerance: 0.5
    cold_tolerance: 0.5
hacs:
  token: !secret hacs_github_token
  sidepanel_title: Community Store
wake_on_lan:
switch:
  - platform: wake_on_lan
    mac: D8:50:E6:01:E3:6F
    name: WOL - Asus
  - platform: wake_on_lan
    mac: 38:22:E2:EF:A2:96
    name: WOL - HP
  - platform: wake_on_lan
    mac: 00:E0:4C:69:3D:29
    name: WOL - Realtek - 3.0
  - platform: wake_on_lan
    mac: 00:E0:4C:68:01:B9
    name: WOL - Realtek - C
  - platform: wake_on_lan
    mac: E4:7D:BD:63:76:86
    name: WOL - Samsung TV